// Generated by Futhark 0.26.0 (prerelease - include info below when reporting bugs).
// git: 7947116 (Mon Nov 17 10:29:28 2025 +0100)
// Compiled with GHC 9.6.7.
#pragma once


// Headers
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <stdio.h>
#include <float.h>
#include <pthread.h>
#ifdef __cplusplus
extern "C" {
#endif

// Initialisation
struct futhark_context_config;
struct futhark_context_config *futhark_context_config_new(void);
void futhark_context_config_free(struct futhark_context_config *cfg);
int futhark_context_config_set_tuning_param(struct futhark_context_config *cfg, const char *param_name, size_t new_value);
struct futhark_context;
struct futhark_context *futhark_context_new(struct futhark_context_config *cfg);
void futhark_context_free(struct futhark_context *ctx);
void futhark_context_config_set_num_threads(struct futhark_context_config *cfg, int n);
void futhark_context_config_set_debugging(struct futhark_context_config *cfg, int flag);
void futhark_context_config_set_profiling(struct futhark_context_config *cfg, int flag);
void futhark_context_config_set_logging(struct futhark_context_config *cfg, int flag);
int futhark_get_tuning_param_count(void);
const char *futhark_get_tuning_param_name(int);
const char *futhark_get_tuning_param_class(int);

// Arrays
struct futhark_i8_2d;
struct futhark_i8_2d *futhark_new_i8_2d(struct futhark_context *ctx, const int8_t *data, int64_t dim0, int64_t dim1);
struct futhark_i8_2d *futhark_new_raw_i8_2d(struct futhark_context *ctx, unsigned char *data, int64_t dim0, int64_t dim1);
int futhark_free_i8_2d(struct futhark_context *ctx, struct futhark_i8_2d *arr);
int futhark_values_i8_2d(struct futhark_context *ctx, struct futhark_i8_2d *arr, int8_t *data);
int futhark_index_i8_2d(struct futhark_context *ctx, int8_t *out, struct futhark_i8_2d *arr, int64_t i0, int64_t i1);
unsigned char *futhark_values_raw_i8_2d(struct futhark_context *ctx, struct futhark_i8_2d *arr);
const int64_t *futhark_shape_i8_2d(struct futhark_context *ctx, struct futhark_i8_2d *arr);
struct futhark_u32_2d;
struct futhark_u32_2d *futhark_new_u32_2d(struct futhark_context *ctx, const uint32_t *data, int64_t dim0, int64_t dim1);
struct futhark_u32_2d *futhark_new_raw_u32_2d(struct futhark_context *ctx, unsigned char *data, int64_t dim0, int64_t dim1);
int futhark_free_u32_2d(struct futhark_context *ctx, struct futhark_u32_2d *arr);
int futhark_values_u32_2d(struct futhark_context *ctx, struct futhark_u32_2d *arr, uint32_t *data);
int futhark_index_u32_2d(struct futhark_context *ctx, uint32_t *out, struct futhark_u32_2d *arr, int64_t i0, int64_t i1);
unsigned char *futhark_values_raw_u32_2d(struct futhark_context *ctx, struct futhark_u32_2d *arr);
const int64_t *futhark_shape_u32_2d(struct futhark_context *ctx, struct futhark_u32_2d *arr);

// Opaque values
struct futhark_opaque_tup2_rng_engine_rng_spin;
struct futhark_opaque_arr2d_tup2_rng_engine_rng_spin;
struct futhark_opaque_state;
int futhark_free_opaque_tup2_rng_engine_rng_spin(struct futhark_context *ctx, struct futhark_opaque_tup2_rng_engine_rng_spin *obj);
int futhark_store_opaque_tup2_rng_engine_rng_spin(struct futhark_context *ctx, const struct futhark_opaque_tup2_rng_engine_rng_spin *obj, void **p, size_t *n);
struct futhark_opaque_tup2_rng_engine_rng_spin *futhark_restore_opaque_tup2_rng_engine_rng_spin(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_tup2_rng_engine_rng_spin_0(struct futhark_context *ctx, uint32_t *out, const struct futhark_opaque_tup2_rng_engine_rng_spin *obj);
int futhark_project_opaque_tup2_rng_engine_rng_spin_1(struct futhark_context *ctx, int8_t *out, const struct futhark_opaque_tup2_rng_engine_rng_spin *obj);
int futhark_new_opaque_tup2_rng_engine_rng_spin(struct futhark_context *ctx, struct futhark_opaque_tup2_rng_engine_rng_spin **out, const uint32_t f_0, const int8_t f_1);
int futhark_free_opaque_arr2d_tup2_rng_engine_rng_spin(struct futhark_context *ctx, struct futhark_opaque_arr2d_tup2_rng_engine_rng_spin *obj);
int futhark_store_opaque_arr2d_tup2_rng_engine_rng_spin(struct futhark_context *ctx, const struct futhark_opaque_arr2d_tup2_rng_engine_rng_spin *obj, void **p, size_t *n);
struct futhark_opaque_arr2d_tup2_rng_engine_rng_spin *futhark_restore_opaque_arr2d_tup2_rng_engine_rng_spin(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_arr2d_tup2_rng_engine_rng_spin_0(struct futhark_context *ctx, struct futhark_u32_2d **out, const struct futhark_opaque_arr2d_tup2_rng_engine_rng_spin *obj);
int futhark_project_opaque_arr2d_tup2_rng_engine_rng_spin_1(struct futhark_context *ctx, struct futhark_i8_2d **out, const struct futhark_opaque_arr2d_tup2_rng_engine_rng_spin *obj);
int futhark_zip_opaque_arr2d_tup2_rng_engine_rng_spin(struct futhark_context *ctx, struct futhark_opaque_arr2d_tup2_rng_engine_rng_spin **out, const struct futhark_u32_2d *f_0, const struct futhark_i8_2d *f_1);
int futhark_index_opaque_arr2d_tup2_rng_engine_rng_spin(struct futhark_context *ctx, struct futhark_opaque_tup2_rng_engine_rng_spin **out, struct futhark_opaque_arr2d_tup2_rng_engine_rng_spin *arr, int64_t i0, int64_t i1);
const int64_t *futhark_shape_opaque_arr2d_tup2_rng_engine_rng_spin(struct futhark_context *ctx, struct futhark_opaque_arr2d_tup2_rng_engine_rng_spin *arr);
int futhark_free_opaque_state(struct futhark_context *ctx, struct futhark_opaque_state *obj);
int futhark_store_opaque_state(struct futhark_context *ctx, const struct futhark_opaque_state *obj, void **p, size_t *n);
struct futhark_opaque_state *futhark_restore_opaque_state(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_state_cells(struct futhark_context *ctx, struct futhark_opaque_arr2d_tup2_rng_engine_rng_spin **out, const struct futhark_opaque_state *obj);
int futhark_new_opaque_state(struct futhark_context *ctx, struct futhark_opaque_state **out, const struct futhark_opaque_arr2d_tup2_rng_engine_rng_spin *f_cells);

// Entry points
int futhark_entry_main(struct futhark_context *ctx, struct futhark_i8_2d **out0, const float in0, const float in1, const int64_t in2, const int64_t in3, const int32_t in4);
int futhark_entry_tui_init(struct futhark_context *ctx, struct futhark_opaque_state **out0, const int32_t in0, const int64_t in1, const int64_t in2);
int futhark_entry_tui_render(struct futhark_context *ctx, struct futhark_i8_2d **out0, const struct futhark_opaque_state *in0);
int futhark_entry_tui_step(struct futhark_context *ctx, struct futhark_opaque_state **out0, const float in0, const float in1, const struct futhark_opaque_state *in2);

// Miscellaneous
int futhark_context_sync(struct futhark_context *ctx);
void futhark_context_config_set_cache_file(struct futhark_context_config *cfg, const char *f);
char *futhark_context_get_error(struct futhark_context *ctx);
void futhark_context_set_logging_file(struct futhark_context *ctx, FILE *f);
void futhark_context_pause_profiling(struct futhark_context *ctx);
void futhark_context_unpause_profiling(struct futhark_context *ctx);
char *futhark_context_report(struct futhark_context *ctx);
int futhark_context_clear_caches(struct futhark_context *ctx);
#define FUTHARK_BACKEND_multicore
#define FUTHARK_SUCCESS 0
#define FUTHARK_PROGRAM_ERROR 2
#define FUTHARK_OUT_OF_MEMORY 3

#ifdef __cplusplus
}
#endif
